# Shell variables
# Generated by 'wal'
wallpaper='/home/nikita/Pictures/wallpapers/amhXFPX.jpeg'

# Special
background='#091119'
foreground='#caabc2'
cursor='#caabc2'

# Colors
color0='#091119'
color1='#2E4B6B'
color2='#4E5273'
color3='#3B5C84'
color4='#526891'
color5='#5A6891'
color6='#887694'
color7='#caabc2'
color8='#8d7787'
color9='#2E4B6B'
color10='#4E5273'
color11='#3B5C84'
color12='#526891'
color13='#5A6891'
color14='#887694'
color15='#caabc2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
